### ISSUE TITLE
PiT 24.0: Changes in Nonnull TS model definition when migrating from 1.3 to 2.0.0.beta4

### ISSUE THREAD

**Issue by manolo** [vaadin/hilla#784]
### Description of the bug 
When migrating an app from `1.3+` to `2.0.0.beta4`, there are compilation errors in the usage of the generated models

### Minimal reproducible example
The following is a start hilla application was generated for platform 23.3 (hilla 1.3), changed dependencies to 2.0.0.beta4 and other documented changes as described in v24 upgrade guide.

[latest-lit.zip](https://github.com/vaadin/hilla/files/10823447/latest-lit.zip)

### Expected behavior
App runs

### Actual behavior
Errors regarding `Nonnull` type definition in TS

```
[ERROR] Stderr: 'vite v4.1.2 building for production...
[ERROR] transforming...
[ERROR] frontend/views/masterdetailsamplebooklit/master-detail-sample-book-lit-view.ts(62,84): error TS2345: Argument of type 'number[] | undefined' is not assignable to parameter of type 'number[]'.
[ERROR]   Type 'undefined' is not assignable to type 'number[]'.
[ERROR] frontend/views/masterdetailsamplebooklit/master-detail-sample-book-lit-view.ts(85,31): error TS2532: Object is possibly 'undefined'.
[ERROR]
```

### Versions:
    - Vaadin / Hilla version: 24.0.0.beta4, 2.0.0.beta4

**Comment by Artur-** [comment]
This is a problem in where the `@Nonnull` is placed in the original code for `byte[]`. It has now been fixed both for 1.3 and 2.0 in start.vaadin.com
