### ISSUE TITLE
PiT 24.1: error compiling hilla start application in prod-mode

### ISSUE THREAD

**Issue by manolo** [vaadin/hilla#878]
### Description of the bug 
When downloading and compiling a new hilla application it fails during ts compilation in prod-mode. It does not happens in dev-mode.

```
Failed to execute goal dev.hilla:hilla-maven-plugin:2.1.0.alpha2:build-frontend (default) on project latest-lit: Execution default of goal dev.hilla:hilla-maven-plugin:2.1.0.alpha2:build-frontend failed: Vite process exited with non-zero exit code.
[ERROR] Stderr: 'vite v4.2.1 building for production...
[ERROR] transforming...
[ERROR] frontend/views/masterdetailsamplebooklit/master-detail-sample-book-lit-view.ts(3,33): error TS2307: Cannot find module '@hilla/form/BinderNode' or its corresponding type declarations.
[ERROR] ✓ 430 modules transformed.
[ERROR] rendering chunks...
[ERROR] ': Unexpected exit value: 2, allowed exit values: [0], executed command 
```
### Minimal reproducible example
1. Download a new app from start
```
curl -s -f 'https://start.vaadin.com/dl?&preset=latest-lit&projectName=latest-lit' -o latest-lit.zip
unzip latest-lit.zip
cd latest-lit
```
2. Change hilla.version from 2.0.3 to 2.1.0.alpha2
4.  Run and compile in dev-mode, it works
```
./mvnw 
```
5. Compile it for production, it fails
```
./mvnw  clean
./mvnw  -Pproduction package 
```
### Expected behavior
It compiles and run
### Versions:
    - Vaadin / Hilla version: 24.1.0.alpha2 / 2.1.0.alpha2

**Comment by Artur-** [comment]
We need to fix this by adding `allowImportingTsExtensions: true` to `tsconfig.json` as it affects not only your project files which you can fix, but also files in `node_modules`, such as `vcf-nav` which contains https://github.com/vaadin/vcf-nav/blob/main/vcf-nav.ts#L1 and stops working with 24.1 alpha2

**Comment by manolo** [comment]
works with SNAPSHOT, keeping opened until next alpha

**Comment by manolo** [comment]
Fixed, does not happen in beta1, closing

**Comment by manolo** [comment]
Reopening Issue, it does not fail with preset `preset=latest-lit` but still fails with `preset=latest-lit&preset=partial-auth`

1. Download starter
```
   curl -s -f 'https://start.vaadin.com/dl?&preset=latest-lit&preset=partial-auth&projectName=latest-lit_partial-auth' -o latest-lit_partial-auth.zip
   unzip latest-lit_partial-auth.zip
   cd latest-lit-partial-auth
```
2. Change version to `24.1.0.beta1` and add pre-releases repo
```
     <properties>
         <java.version>17</java.version>
-        <hilla.version>2.0.4</hilla.version>
+        <hilla.version>2.1.0.beta1</hilla.version>
         <selenium.version>4.8.3</selenium.version>
     </properties>
+    <pluginRepositories><pluginRepository><id>v</id><url>https://maven.vaadin.com/vaadin-prereleases/</url></pluginRepository></pluginRepositories>
+    <repositories><repository><id>v</id><url>https://maven.vaadin.com/vaadin-prereleases/</url></repository></repositories>
```
3. Compile the app for production
```
./mvnw -Pproduction package
```
4. See error
```
2023-05-23T14:49:51.610+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :  FILE  /Users/manolo/Github/platform/platform-in-test-script/tmp/latest-lit_partial-auth/frontend/views/login/login-view.ts:15:3
2023-05-23T14:49:51.610+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :
2023-05-23T14:49:51.610+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     13 |     forgotPassword: 'Forgot password',
2023-05-23T14:49:51.610+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     14 |   },
2023-05-23T14:49:51.610+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   > 15 |   errorMessage: {
2023-05-23T14:49:51.610+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :        |   ^^^^^^^^^^^^
2023-05-23T14:49:51.610+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     16 |     title: 'Incorrect username or password',
2023-05-23T14:49:51.610+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     17 |     message: 'Check that you have entered the correct username and password and try again.',
2023-05-23T14:49:51.610+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     18 |   },
2023-05-23T14:49:51.610+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :
2023-05-23T14:49:51.610+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :  ERROR(TypeScript)  An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is enabled.
2023-05-23T14:49:51.610+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :  FILE  /Users/manolo/Github/platform/platform-in-test-script/tmp/latest-lit_partial-auth/node_modules/@vaadin-component-factory/vcf-nav/vcf-nav.ts:1:8
2023-05-23T14:49:51.611+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :
2023-05-23T14:49:51.611+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   > 1 | import './src/vcf-nav.ts';
2023-05-23T14:49:51.611+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       |        ^^^^^^^^^^^^^^^^^^
2023-05-23T14:49:51.611+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     2 | import './src/vcf-nav-item.ts';
2023-05-23T14:49:51.611+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     3 |
2023-05-23T14:49:51.611+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :
2023-05-23T14:49:51.611+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :  ERROR(TypeScript)  An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is enabled.
2023-05-23T14:49:51.611+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :  FILE  /Users/manolo/Github/platform/platform-in-test-script/tmp/latest-lit_partial-auth/node_modules/@vaadin-component-factory/vcf-nav/vcf-nav.ts:2:8
2023-05-23T14:49:51.611+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :
2023-05-23T14:49:51.611+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     1 | import './src/vcf-nav.ts';
2023-05-23T14:49:51.611+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   > 2 | import './src/vcf-nav-item.ts';
2023-05-23T14:49:51.611+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       |        ^^^^^^^^^^^^^^^^^^^^^^^
2023-05-23T14:49:51.611+02:00  INFO 88110 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     3 |
```

**Comment by platosha** [comment]
I got this error:
```
[ERROR] frontend/views/login/login-view.ts(15,3): error TS2739: Type '{ title: string; message: string; }' is missing the following properties from type '{ title: string; message: string; username: string; password: string; }': username, password
```
This was addressed in 24.1.0.beta2 of the web component, so the error should be gone after a new beta release.

Let's keep this open for now before Hilla v2.1.0.beta2 is out.

**Comment by manolo** [comment]
So, compilation for production has been fixed in `beta3` 

But there is still a problem with https://github.com/vaadin/vcf-nav,  in dev-mode it shows the error, though in production mode it does not happen. The way to fix it is adding the `allowImportingTsExtensions: true`, but not updating the component to latest version `1.1.1` 

Obviously it only happens when upgrading start apps from 2.0 to 2.1 because downloading pre apps do not bring the vcf component.

So what should we do with this issue, should we document it? or just keep the user to read the error message and do what it suggests 
```
ERROR(TypeScript)  An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is enabled.
```
I guess we can add this note to the 24.1 release-notes

New and Noteworthy Since Vaadin 23.1
- Design System
  - New component: Multi-Select Combo Box
  NOTE: If you project uses the `vcf-nav` component, replace it with `vaadin-side-nav`

**Comment by platosha** [comment]
I suggest that we update the `vcf-nav` and compile it to JS. This would enable a clean way to deal with this issue for the users, they would have to bump the version to `1.1.2`, without resorting to `allowImportingTsExtensions`.

**Comment by platosha** [comment]
At the same time we can deprecate `1.1.0` and `1.1.1` on npm, so that a warning shows up for the users, thus giving them a hint to bump the version.

**Comment by Artur-** [comment]
If we have not identified any other need for `allowImportingTsExtensions` then it sounds reasonable to fix vcf-nav instead of adding the option by default

The release notes should either way mention:
1. It is recommended to migrate from vcf-nav to vaadin-side-nav
2. That if you see `An import path can only end with a '.ts' extension when 'allowImportingTsExtensions'...` then you should fix the import (ts -> js) and if that is not under your control, then you can add `allowImportingTsExtensions: true` to `tsconfig.json`
