### ISSUE TITLE
PiT 24.0: cannot run any hilla app in when bumping to 2.0.0.beta3

### ISSUE THREAD

**Issue by manolo** [vaadin/hilla#771]
### Description of the bug 
Migrating Hilla apps from 1.3.0 or from 2.0.0.beta2 to 2.0.0.beta3, there are console errors regarding endopoints not found

```
ERROR(TypeScript)  Cannot find module 'Frontend/generated/HelloWorldEndpoint' or its corresponding type declarations.
```

### Minimal reproducible example

- Uncompress and run the following example:
[latest-lit.zip](https://github.com/vaadin/hilla/files/10793491/latest-lit.zip)
- Run the app `mvn` 

It was generated by:

- Going to https://start.vaadin.com 
- Selecting Vaadin V24 (pre) in the technology section
- Removing default views, and add 'Hello world using Hilla' and optionally  'Master Detail using Hilla'
- Download, uncompress
- Bump version `<hilla.version>2.0.0.beta3</hilla.version>` 

### Expected behavior
App should work
### Actual behavior
TS errors in console
### Versions:
    - Vaadin / Hilla version: 2.0.0.beta3

**Comment by platosha** [comment]
Could be caused by missing a Java service registration for `packages/java/engine-runtime/src/main/java/dev/hilla/internal/EndpointGeneratorTaskFactoryImpl.java`.

**Comment by manolo** [comment]
Shouldn't that registration come within a `.jar` so as the user doesn't have to do ?

**Comment by cromoteca** [comment]
This is already fixed in https://github.com/vaadin/hilla/pull/767

**Comment by manolo** [comment]
I tried with `2.0-SNAPSHOT` and still failing, 

```
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< com.example.application:latest-lit >-----------------
[INFO] Building latest-lit 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.3.0:resources (default-resources) @ latest-lit ---
[INFO] Copying 1 resource
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ latest-lit ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- hilla-maven-plugin:2.0-SNAPSHOT:prepare-frontend (default) @ latest-lit ---
[WARNING] The productionMode parameter no longer has any effect. Production mode is automatically enabled when you run the build-frontend target.
[INFO] The globally installed Node.js version 16.19.0 is older than the required minimum version 18.0.0. Using Node.js from /home/runner/.vaadin.
[INFO] Reflections took 2730 ms to scan 164 urls, producing 9768 keys and 50512 values
[INFO] Copying frontend resources from jar files ...
[INFO] Visited 163 resources. Took 126 ms.
[INFO] 
[INFO] --- hilla-maven-plugin:2.0-SNAPSHOT:build-frontend (default) @ latest-lit ---
[INFO] Reflections took 1807 ms to scan 164 urls, producing 9768 keys and 50512 values
[INFO] Scanning classes to find frontend configurations and dependencies...
[INFO] Visited 742 classes. Took 885 ms.
[INFO] Visited 9 classes. Took 45 ms.
[INFO] Unable to determine version information. No vaadin-core-versions.json found
[INFO] Skipping `npm install` because the frontend packages are already installed in the folder '/home/runner/work/platform/platform/tmp/latest-lit/node_modules' and the hash in the file '/home/runner/work/platform/platform/tmp/latest-lit/node_modules/.vaadin/vaadin.json' is the same as in 'package.json'
[INFO] Hilla engine configuration not found: configure using build system plugin
[INFO] JVM Parser started
[INFO] Search for endpoints in directories [/home/runner/work/platform/platform/tmp/latest-lit/target/classes]
[INFO] JVM Parser finished successfully
�[32mINFO�[39m (tsgen): �[36mOutput directory: /home/runner/work/platform/platform/tmp/latest-lit/frontend/generated�[39m
�[32mINFO�[39m (tsgen): �[36mPlugins: BackbonePlugin, ClientPlugin, BarrelPlugin, ModelPlugin, PushPlugin�[39m
�[32mINFO�[39m (tsgen) : �[36mGenerating 'endpoints.ts' file�[39m
[INFO] The Generator process finished with the exit code 0
[INFO] Copying frontend resources from jar files ...
[INFO] Visited 163 resources. Took 51 ms.
[INFO] Reflections took 2036 ms to scan 164 urls, producing 9768 keys and 50512 values
[INFO] The globally installed Node.js version 16.19.0 is older than the required minimum version 18.0.0. Using Node.js from /home/runner/.vaadin.
[INFO] Running Vite ...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.465 s
[INFO] Finished at: 2023-02-22T07:31:12Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal dev.hilla:hilla-maven-plugin:2.0-SNAPSHOT:build-frontend (default) on project latest-lit: Execution default of goal dev.hilla:hilla-maven-plugin:2.0-SNAPSHOT:build-frontend failed: Vite process exited with non-zero exit code.
[ERROR] Stderr: 'vite v4.1.2 building for production...
[ERROR] transforming...
[ERROR] frontend/views/masterdetaillit/master-detail-lit-view.ts(22,23): error TS2307: Cannot find module 'Frontend/generated/dev/hilla/mappedtypes/Sort' or its corresponding type declarations.
[ERROR] frontend/views/masterdetailsampleaddresslit/master-detail-sample-address-lit-view.ts(21,23): error TS2307: Cannot find module 'Frontend/generated/dev/hilla/mappedtypes/Sort' or its corresponding type declarations.
[ERROR] frontend/views/masterdetailsamplebooklit/master-detail-sample-book-lit-view.ts(25,23): error TS2307: Cannot find module 'Frontend/generated/dev/hilla/mappedtypes/Sort' or its corresponding type declarations.
[ERROR] frontend/views/masterdetailsamplebooklit/master-detail-sample-book-lit-view.ts(62,84): error TS2345: Argument of type 'number[] | undefined' is not assignable to parameter of type 'number[]'.
[ERROR]   Type 'undefined' is not assignable to type 'number[]'.
[ERROR] frontend/views/masterdetailsamplebooklit/master-detail-sample-book-lit-view.ts(85,31): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/views/masterdetailsamplebooklit/master-detail-sample-book-lit-view.ts(86,45): error TS2345: Argument of type 'number[] | undefined' is not assignable to parameter of type 'number[]'.
[ERROR]   Type 'undefined' is not assignable to type 'number[]'.
[ERROR] ': Unexpected exit value: 2, allowed exit values: [0], executed command [/home/runner/.vaadin/node/node, /home/runner/work/platform/platform/tmp/latest-lit/node_modules/vite/bin/vite.js, build] in directory /home/runner/work/platform/platform/tmp/latest-lit with environment {PATH=/home/runner/.vaadin/node:/opt/hostedtoolcache/maven/3.8.2/x64/bin:/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.6-10/x64/bin:/opt/hostedtoolcache/node/16.19.0/x64/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin, GITHUB_REPOSITORY_OWNER=vaadin, SWIFT_PATH=/usr/share/swift/usr/bin, SGX_AESM_ADDR=1, GITHUB_REPOSITORY_ID=91825645, CHROMEWEBDRIVER=/usr/local/share/chrome_driver, RUNNER_USER=runner, GITHUB_RUN_NUMBER=119, ANDROID_HOME=/usr/local/lib/android/sdk, GITHUB_WORKSPACE=/home/runner/work/platform/platform, GITHUB_RETENTION_DAYS=90, GITHUB_API_URL=https://api.github.com, GITHUB_RUN_ATTEMPT=1, *** GITHUB_JOB=run, GITHUB_ACTIONS=true, DOTNET_MULTILEVEL_LOOKUP=0, HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS=3650, STATS_RDCL=true, ANDROID_NDK=/usr/local/lib/android/sdk/ndk/25.2.9519653, GOROOT_1_18_X64=/opt/hostedtoolcache/go/1.18.10/x64, GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_82a3f06e-ae25-460c-8cb3-bdb2c91ccacd, GRAALVM_11_ROOT=/usr/local/graalvm/graalvm-ce-java11-22.3.1, GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json, GITHUB_ACTOR_ID=161853, GITHUB_REF_TYPE=branch, GHTK=***, RUNNER_TOOL_CACHE=/opt/hostedtoolcache, SHLVL=2, LEIN_HOME=/usr/local/lib/lein, STATS_NM=true, GITHUB_SERVER_URL=https://github.com, JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.6-10/x64, GITHUB_REF=refs/heads/main, RUNNER_NAME=GitHub Actions 12, BOOTSTRAP_HASKELL_NONINTERACTIVE=1, GRADLE_HOME=/usr/share/gradle-8.0, ANT_HOME=/usr/share/ant, GITHUB_OUTPUT=/home/runner/work/_temp/_runner_file_commands/set_output_82a3f06e-ae25-460c-8cb3-bdb2c91ccacd, JAVA_HOME_17_X64=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.6-10/x64, GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_82a3f06e-ae25-460c-8cb3-bdb2c91ccacd, GITHUB_REPOSITORY=vaadin/platform, GITHUB_ACTION_REF=, _=/opt/hostedtoolcache/maven/3.8.2/x64/bin/mvn, AZURE_EXTENSION_DIR=/opt/az/azcliextensions, CI=true, DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1, LEIN_JAR=/usr/local/lib/lein/self-installs/leiningen-2.10.0-standalone.jar, MAVEN_PROJECTBASEDIR=/home/runner/work/platform/platform/tmp/latest-lit, RUNNER_ARCH=X64, GITHUB_SHA=bcd4cf010a12516a484a2734ff386b52a0815186, ImageOS=ubuntu22, ImageVersion=20230217.1, ACCEPT_EULA=Y, RUNNER_PERFLOG=/home/runner/perflog, PERFLOG_LOCATION_SETTING=RUNNER_PERFLOG, RUNNER_TRACKING_ID=github_5de77f7a-0fbf-4a10-99b5-84d0729365ac, RUNNER_WORKSPACE=/home/runner/work/platform, INVOCATION_ID=772d1c2ef8744e96ab95fd4dbe8c8612, GITHUB_REF_PROTECTED=true, EDGEWEBDRIVER=/usr/local/share/edge_driver, GITHUB_WORKFLOW=PiT, CONDA=/usr/share/miniconda, SELENIUM_JAR_PATH=/usr/share/java/selenium-server.jar, GITHUB_BASE_REF=, PIPX_HOME=/opt/pipx, JOURNAL_STREAM=8:16930, GITHUB_WORKFLOW_SHA=bcd4cf010a12516a484a2734ff386b52a0815186, GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_82a3f06e-ae25-460c-8cb3-bdb2c91ccacd, GITHUB_EVENT_NAME=workflow_dispatch, GITHUB_TRIGGERING_ACTOR=manolo, CHROME_BIN=/usr/bin/google-chrome, GOROOT_1_17_X64=/opt/hostedtoolcache/go/1.17.13/x64, AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache, ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/25.2.9519653, ANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk/25.2.9519653, VCPKG_INSTALLATION_ROOT=/usr/local/share/vcpkg, GITHUB_GRAPHQL_URL=https://api.github.com/graphql, OLDPWD=/home/runner/work/platform/platform/tmp/latest-lit, RUNNER_OS=Linux, DOTNET_NOLOGO=1, DEBIAN_FRONTEND=noninteractive, GITHUB_WORKFLOW_REF=vaadin/platform/.github/workflows/pit.yml@refs/heads/main, GITHUB_ACTION=__run_5, POWERSHELL_DISTRIBUTION_CHANNEL=GitHub-Actions-ubuntu22, GITHUB_ACTOR=manolo, SYSTEMD_EXEC_PID=659, GOROOT_1_19_X64=/opt/hostedtoolcache/go/1.19.5/x64, PIPX_BIN_DIR=/opt/pipx_bin, GECKOWEBDRIVER=/usr/local/share/gecko_driver, JAVA_HOME_8_X64=/usr/lib/jvm/temurin-8-jdk-amd64, LANG=C.UTF-8, GITHUB_REPOSITORY_OWNER_ID=1171922, MAVEN_OPTS= , GHCUP_INSTALL_BASE_PREFIX=/usr/local, GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_82a3f06e-ae25-460c-8cb3-bdb2c91ccacd, MAVEN_CMD_LINE_ARGS= -ntp -B -Pproduction package -Dmaven.compiler.showDeprecation, GITHUB_REF_NAME=main, NVM_DIR=/home/runner/.nvm, ANDROID_NDK_LATEST_HOME=/usr/local/lib/android/sdk/ndk/25.2.9519653, DEPLOYMENT_BASEPATH=/opt/runner, HOMEBREW_NO_AUTO_UPDATE=1, GITHUB_ACTION_REPOSITORY=, ANDROID_SDK_ROOT=/usr/local/lib/android/sdk, GITHUB_RUN_ID=4240380290, USER=runner, XDG_CONFIG_HOME=/home/runner/.config, RUNNER_TEMP=/home/runner/work/_temp, GITHUB_HEAD_REF=, JAVA_HOME_11_X64=/usr/lib/jvm/temurin-11-jdk-amd64, XDG_RUNTIME_DIR=/run/user/1001, HOME=/home/runner}, output was 1314 bytes:
[ERROR] [36mvite v4.1.2 building for production...
[ERROR] transforming...
[ERROR] frontend/views/masterdetaillit/master-detail-lit-view.ts(22,23): error TS2307: Cannot find module 'Frontend/generated/dev/hilla/mappedtypes/Sort' or its corresponding type declarations.
[ERROR] frontend/views/masterdetailsampleaddresslit/master-detail-sample-address-lit-view.ts(21,23): error TS2307: Cannot find module 'Frontend/generated/dev/hilla/mappedtypes/Sort' or its corresponding type declarations.
[ERROR] frontend/views/masterdetailsamplebooklit/master-detail-sample-book-lit-view.ts(25,23): error TS2307: Cannot find module 'Frontend/generated/dev/hilla/mappedtypes/Sort' or its corresponding type declarations.
[ERROR] frontend/views/masterdetailsamplebooklit/master-detail-sample-book-lit-view.ts(62,84): error TS2345: Argument of type 'number[] | undefined' is not assignable to parameter of type 'number[]'.
[ERROR]   Type 'undefined' is not assignable to type 'number[]'.
[ERROR] frontend/views/masterdetailsamplebooklit/master-detail-sample-book-lit-view.ts(85,31): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/views/masterdetailsamplebooklit/master-detail-sample-book-lit-view.ts(86,45): error TS2345: Argument of type 'number[] | undefined' is not assignable to parameter of type 'number[]'.
[ERROR]   Type 'undefined' is not assignable to type 'number[]'.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```
