### ISSUE TITLE
PiT 24.0: vite compilation error `./vaadin-featureflags.ts` does not exist

### ISSUE THREAD

**Issue by manolo** [vaadin/hilla#742]
### Description of the bug 

When migrating a hilla app from 1.3 to 2.0.0.alpha10 there is a compilation error

```
[vite] Internal server error: Failed to resolve import "./vaadin-featureflags.ts" from "frontend/generated/vaadin.ts". Does the file exist?
Plugin: vite:import-analysis
File: /Users/manolo/Github/platform/platform-in-test-script/tmp/latest-lit/frontend/generated/vaadin.ts:1:7
1  |  import "./vaadin-featureflags.ts";
   |          ^
2  |  import "../index";
3  |  import "Frontend/generated/jar-resources/vaadin-dev-tools/vaadin-dev-tools.js";
```

### Minimal reproducible example
```
curl -s -f 'https://start.vaadin.com/dl?&preset=latest-lit&projectName=latest-lit' -o latest-lit.zip
unzip latest-lit.zip

cd latest-lit


mvn -B -q versions:set-property -Dproperty=hilla.version -DnewVersion=2.0.0.alpha10
mvn -q versions:update-parent -DparentVersion=3.0.2
mvn -B -q versions:set-property -Dproperty=java.version -DnewVersion=17
find src/main -name "*.java" | xargs perl -pi -e 's/javax\.(persistence|validation|annotation|transaction|inject|servlet)/jakarta.$1/g'

mvn
```

### Expected behavior
App works

### Actual behavior
Compilation error

### Versions:
    - Vaadin / Hilla version: 24.0.0.alpha10 2.0.0.alpha10
    - Node version:
    - Java version:
    - OS version:
    - Browser version (if applicable):
    - Application Server (if applicable):
    - IDE/Editor (if applicable):
