### PR TITLE
feat: align endpoint discovery strategy and make it configurable

### LINKED ISSUE #697: Incoherent behavior between generator and controller while searching for endpoints
### Description of the bug 

Endpoints are searched in all packages and translated to TypeScript, but then, when the application is executed, The endpoint registry in the controller is populated using `getBeansWithAnnotation` which only searches the Spring Boot application package by default. So, any endpoint outside of that is available when writing code, but not at execution time.

### Minimal reproducible example

Create a Hilla application and move `HelloWorldEndpoint` outside of `com.example.application`.

### Expected behavior

Either the endpoint is still accessible, or it is not translated to TypeScript at all.

### Actual behavior

TS is generated, but a 404 is returned at any invocation.

### Versions
Basically any recent version. Changing generator makes no difference.

### Workaround
Tell Spring to search inside the new package:

```java
@SpringBootApplication(scanBasePackages = { "com.example.application", "com.example.myendpoints" })
```

### LINKED ISSUE #771: PiT 24.0: cannot run any hilla app in when bumping to 2.0.0.beta3
### Description of the bug 
Migrating Hilla apps from 1.3.0 or from 2.0.0.beta2 to 2.0.0.beta3, there are console errors regarding endopoints not found

```
ERROR(TypeScript)  Cannot find module 'Frontend/generated/HelloWorldEndpoint' or its corresponding type declarations.
```

### Minimal reproducible example

- Uncompress and run the following example:
[latest-lit.zip](https://github.com/vaadin/hilla/files/10793491/latest-lit.zip)
- Run the app `mvn` 

It was generated by:

- Going to https://start.vaadin.com 
- Selecting Vaadin V24 (pre) in the technology section
- Removing default views, and add 'Hello world using Hilla' and optionally  'Master Detail using Hilla'
- Download, uncompress
- Bump version `<hilla.version>2.0.0.beta3</hilla.version>` 

### Expected behavior
App should work
### Actual behavior
TS errors in console
### Versions:
    - Vaadin / Hilla version: 2.0.0.beta3

### PR DESCRIPTION
**Pull request by cromoteca**
Closes #697
Fixes #771

Endpoints are searched in `target` unless a whitelist of packages is defined in `pom.xml`.
Endpoint classes are now added to `openapi.json` which is available in the classpath.
This information is used to register the endpoints at runtime.
A workaround is in place if an endpoint cannot be loaded as a Spring Bean, provided that this endpoint has a no-args constructor.

Other fixes are included in this PR:
- remove the `build-frontend` goal from tests to align with real applications;
- stop using the `hillaEngine` feature flag in the GitHub workflow;

### CODE REVIEW

**Review by platosha — DISMISSED** [review]

File: packages/java/tests/spring/endpoints-discovery/src/main/resources/vaadin-featureflags.properties [hunk 1]
```diff
@@ -0,0 +1,2 @@
+# Push support in Hilla
+com.vaadin.experimental.hillaPush=true
```
[the remark this answers is not in the document]
Comment (cromoteca) [reply packages/java/tests/spring/endpoints-discovery/src/main/resources/vaadin-featureflags.properties:2]: It's there by mistake, I'll remove it

**Review by Lodin — APPROVED** [review]
