### ISSUE TITLE
PiT 24.4: Error ESM file cannot be loaded by `require` when importing `@vaadin/hilla-file-router/vite-plugin.js`

### ISSUE THREAD

**Issue by manolo** [vaadin/hilla#2193]
### Describe the bug

When updating skeleton-starter-hilla-lit-gradle to 24.4.0.alpha9 there is a frontend compilation error

```
Startup of Vite failed. Output was:
✘ [ERROR] "@vaadin/hilla-file-router/vite-plugin.js" resolved to an ESM file. ESM file cannot be loaded by `require`. See https://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details. [plugin externalize-deps]

    node_modules/esbuild/lib/main.js:1373:27:
      1373 │         let result = await callback({
           ╵                            ^
```

### Expected-behavior

no compilation error

### Reproduction

checkout branch https://github.com/vaadin/skeleton-starter-hilla-lit-gradle/tree/update-to-v24.4 and run `./gradlew bootRun` twice (first time it updates the 'types.d.ts' and throws)

### System Info

24.4.0.alpha9

**Comment by manolo** [comment]
closing in favor of https://github.com/vaadin/flow/issues/18924
