### ISSUE TITLE
Typescript Generator Error for Generic Class with Type Parameterization:  Type 'unknown' does not satisfy the constraint 'Record<never, never>'.

### ISSUE THREAD

**Issue by egloffmark** [vaadin/hilla#1650]
### Describe the bug

Dear all I am using for my Hilla endpoint classes which are derived from an abstract generic class with a type parameter. Since Hilla 2.3.x the typescript generator raises an exception `error TS2344: Type 'unknown' does not satisfy the constraint 'Record<never, never>'.`

I also tried with `@JsonIgnoreType` at class level, but it seems not to work.

My Base Class And Return Type Class
```
@EqualsAndHashCode(callSuper = false)
public abstract class AbstractEntityDto<K> implements Serializable {
	private static final long serialVersionUID = 1L;

	@Getter
	@Setter
	K id;
}

@EqualsAndHashCode(callSuper = true)
public class ProductCategoryDto extends AbstractEntityDto<Integer> {
	private static final long serialVersionUID = 1L;

	@Getter
	@Setter
	private String category;
}
``` 

My Example Endpoint Class:
``` 
@Endpoint
@AnonymousAllowed
public class ProductCategoryEndpoint  {
	public @Nonnull List<@Nonnull ProductCategoryDto> getProductCategories() {
		List<ProductCategoryDto> result = repo.getProductCategories().mapDto();
		return result;
	}
}
``` 
This ends into the following error durign the type script generation with Hilla 2.3.x
``` 
vite v4.4.11 building for production...
AbstractEntityDtoModel.ts(6,29): error TS2344: Type 'unknown' does not satisfy the constraint 'Record<never, never>'.
``` 
### Expected-behavior

Support for Parametrized Classes or clear documentation how to deal with such cases.

### Reproduction

1. Use a Hilla Demo and create an endpoint which uses as return type a derived class from a generic parametrized type class (see above)
2.  Test it with Hilla 2.2.2 and Hilla 2.3.2 

The application works with Hilla 2.2.2 although the type generated classes looks quite similar

Hilla 2.2.2 generates the following "AbstractEntityDtoModel.ts" which gets accepted by vite 
```
import { _getPropertyModel as _getPropertyModel_1, ObjectModel as ObjectModel_1 } from "@hilla/form";
import type AbstractEntityDto_1 from "./AbstractEntityDto.js";
class AbstractEntityDtoModel<T extends AbstractEntityDto_1 = AbstractEntityDto_1>  {
    declare static createEmptyValue: () => AbstractEntityDto_1;
    get id(): ObjectModel_1<unknown> {
        return this[_getPropertyModel_1]("id", ObjectModel_1, [false]) as ObjectModel_1<unknown>;
    }
}
export default AbstractEntityDtoModel;

```
Hilla 2.3.2 generates the following "AbstractEntityDtoModel.ts" and vite ts claims about the `<unknown>` for `get id()` function:
```
import { _getPropertyModel as _getPropertyModel_1, makeObjectEmptyValueCreator as makeObjectEmptyValueCreator_1, ObjectModel as ObjectModel_1 } from "@hilla/form";
import type AbstractEntityDto_1 from "./AbstractEntityDto.js";
class AbstractEntityDtoModel<T extends AbstractEntityDto_1 = AbstractEntityDto_1>  {
    static override createEmptyValue = makeObjectEmptyValueCreator_1(AbstractEntityDtoModel);
    get id(): ObjectModel_1<unknown> {
        return this[_getPropertyModel_1]("id", (parent, key) => new ObjectModel_1(parent, key, false));
    }
}
export default AbstractEntityDtoModel;
```

### System Info

Hilla 2.3.2
Java 17
Windows 11 Home
Firefox

**Comment by platosha** [comment]
Duplicate of #1612

**Comment by platosha** [comment]
Thanks for reporting. Could you, please, try if the issue still occur with Hilla 2.3.3?

**Comment by egloffmark** [comment]
Thank you !  yes with hilla 2.3.3 it works out of the box without changes to my code. Excellent.
