### PR TITLE
fix(parser-jvm-plugin-nonnull): support array nested type annotations

### LINKED ISSUE #784: PiT 24.0: Changes in Nonnull TS model definition when migrating from 1.3 to 2.0.0.beta4
### Description of the bug 
When migrating an app from `1.3+` to `2.0.0.beta4`, there are compilation errors in the usage of the generated models

### Minimal reproducible example
The following is a start hilla application was generated for platform 23.3 (hilla 1.3), changed dependencies to 2.0.0.beta4 and other documented changes as described in v24 upgrade guide.

[latest-lit.zip](https://github.com/vaadin/hilla/files/10823447/latest-lit.zip)

### Expected behavior
App runs

### Actual behavior
Errors regarding `Nonnull` type definition in TS

```
[ERROR] Stderr: 'vite v4.1.2 building for production...
[ERROR] transforming...
[ERROR] frontend/views/masterdetailsamplebooklit/master-detail-sample-book-lit-view.ts(62,84): error TS2345: Argument of type 'number[] | undefined' is not assignable to parameter of type 'number[]'.
[ERROR]   Type 'undefined' is not assignable to type 'number[]'.
[ERROR] frontend/views/masterdetailsamplebooklit/master-detail-sample-book-lit-view.ts(85,31): error TS2532: Object is possibly 'undefined'.
[ERROR]
```

### Versions:
    - Vaadin / Hilla version: 24.0.0.beta4, 2.0.0.beta4

### PR DESCRIPTION
**Pull request by platosha**
Fixes #784

### CODE REVIEW

**Comment by Lodin** [comment]
It looks like a feature, not a bug:
https://stackoverflow.com/questions/29011893/how-to-annotate-an-array-nonnull
```java
@NonNull Object [] o1;

o1    = null;           // OK
o1    = new Object[1];
o1[0] = null;           // NOT OK

Object @NonNull[] o2;

o2    = null;           // NOT OK
o2    = new Object[1];
o2[0] = null;           // OK
```
