### ISSUE TITLE
PiT 24.4: in gradle project when using`vaadin.productionMode`, usage of 'ViewRoute[]' fails to compile

### ISSUE THREAD

**Issue by manolo** [vaadin/hilla#2210]
### Describe the bug

When upgrading `skeleton-starter-hilla-lit-gradle` to 24.4.0.alpha13 there is a frontend compilation error in production mode (when `-Pvaadin.productionMode` is provided)

```
Execution failed for task ':vaadinBuildFrontend'.
> Vite process exited with non-zero exit code.
  Stderr: 'The directory of route files: file:///home/runner/work/platform/platform/tmp/skeleton-starter-hilla-lit-gradle/frontend/views/
  The directory of generated files: file:///home/runner/work/platform/platform/tmp/skeleton-starter-hilla-lit-gradle/frontend/generated/
  The output directory: file:///home/runner/work/platform/platform/tmp/skeleton-starter-hilla-lit-gradle/build/resources/main/META-INF/VAADIN/webapp
  vite v5.1.6 building for production...
  The file "file:///home/runner/work/platform/platform/tmp/skeleton-starter-hilla-lit-gradle/frontend/views/helloworld/hello-world-view.ts" should contain a default export of a component
  The file "file:///home/runner/work/platform/platform/tmp/skeleton-starter-hilla-lit-gradle/frontend/views/about/about-view.ts" should contain a default export of a component
  The file "file:///home/runner/work/platform/platform/tmp/skeleton-starter-hilla-lit-gradle/frontend/views/view.ts" should contain a default export of a component
  The file "file:///home/runner/work/platform/platform/tmp/skeleton-starter-hilla-lit-gradle/frontend/views/main-layout.ts" should contain a default export of a component
  Collected file-based routes
  Frontend route list is generated: file:///home/runner/work/platform/platform/tmp/skeleton-starter-hilla-lit-gradle/build/resources/main/META-INF/VAADIN/views.json
  Views module is generated: file:///home/runner/work/platform/platform/tmp/skeleton-starter-hilla-lit-gradle/frontend/generated/views.ts
  transforming...
  ✓ 302 modules transformed.
  rendering chunks...
  frontend/generated/flow/Flow.tsx(273,39): error TS2345: Argument of type 'ViewRoute[]' is not assignable to parameter of type 'AgnosticRouteObject[]'.
  '
```

### Expected-behavior

App works

### Reproduction

use [this starter branch](https://github.com/vaadin/skeleton-starter-hilla-lit-gradle/tree/update-to-v24.4) or the steps below

```
  # Clone this project
   git clone https://github.com/vaadin/skeleton-starter-hilla-lit-gradle.git
   cd skeleton-starter-hilla-lit-gradle

   # Replace variable hillaVersion with vaadinVersion in build files
   perl -pi -e 's|hillaVersion|vaadinVersion|' build.gradle settings.gradle gradle.properties

   # Bump version from hilla 2.5 to vaadin 24.4
   perl -pi -e 's|\s*(vaadinVersion)\s*([=:]).*|${1}${2}24.4.0.alpha13|g' gradle.properties

   # Change namespace and names in build files
   perl -pi -e 's|dev\.hilla:hilla-bom|com.vaadin:vaadin-bom|' build.gradle
   perl -pi -e 's|dev\.hilla:hilla-(react-)?spring-boot-starter|com.vaadin:vaadin-spring-boot-starter|' build.gradle
   perl -pi -e 's|dev\.hilla|com.vaadin|' build.gradle 
   # Change namespace in java files
   find src/main -name '*.java' -exec perl -pi -e 's/import dev.hilla/import com.vaadin.hilla/g' '{}' ';'

   # Compile for production and it FAILS because modifications in types.d.ts
   ./gradlew clean build -Pvaadin.productionMode
   # Compile again and it FAILS because error above
   ./gradlew clean build -Pvaadin.productionMode


```

### System Info

Vaadin 24.4.0.alpha
