### ISSUE TITLE
Type `StringModel` cannot be used as a model for enum

### ISSUE THREAD

**Issue by Lodin** [vaadin/hilla#552]
Regression created by #548 that follows #542. Now the generation is done correctly but TypeScript is upset about that type `string` is not assignable to `enum` values. 

Minimal reproducible example:

- Run `npx @vaadin/cli init --hilla --auth hilla-with-auth`
- Add `com.vaadin.experimental.hillaEngine=true` to `src/main/resources/vaadin-featureflags.properties`
- Run `npm install`
- Run `mvn spring-boot:run`

You will get the following failure:

```
error TS2344: Type 'StringModel' does not satisfy the constraint 'AbstractModel<Role>'.
  The types returned by 'valueOf()' are incompatible between these types.
    Type 'string' is not assignable to type 'Role'.

16     get roles(): ArrayModel_1<Role_1, StringModel_1> {
```
